//! Simple command Tauri commands.
//!
//! Commands are sent to the session as CI (Command Input) frames:
//! `{"id":"<call-id>","name":"<command>","input":"<args-string>"}`.
//! Results arrive asynchronously as CO (Command Output) frames with the
//! same `id`, which the frontend renders (see reader.rs / Handlers.elm).
//! Uses the `send_cmd!` macro for fixed, argument-less commands.

use crate::alayacore;
use crate::commands::{send_cmd, SessionMap};
use crate::send_cmd;

use serde::Serialize;
use tauri::State;

// Simple commands with fixed text (generated by send_cmd! macro)
send_cmd!(alayacore_cancel, "cancel");

/// Startup check: the frontend probes this on init() so the home screen
/// can show a "AlayaCore not found" banner when the binary is missing,
/// instead of letting the user click New Session and only learn at
/// spawn time (where the error silently breaks the UI).
///
/// `find_binary()` already filters most paths by `.exists()`; the only
/// branch that returns a non-existent path is the fallback ("alayacore"
/// on PATH, which is not stat'd). We stat the returned path one more
/// time so the result is decisive: if a stale `ALAYACORE_BIN` env var
/// points to a deleted file, the env-var AND the `which` AND the
/// candidate paths would all fail — the user gets a clear error
/// pointing at the exact path that was tried.
#[derive(Serialize)]
pub struct AlayacoreCheck {
    pub ok: bool,
    pub path: String,
    pub error: String,
}

#[tauri::command]
pub fn check_alayacore() -> AlayacoreCheck {
    let path = alayacore::find_binary();
    match std::path::Path::new(&path).metadata() {
        Ok(_) => AlayacoreCheck {
            ok: true,
            path,
            error: String::new(),
        },
        Err(_) => AlayacoreCheck {
            ok: false,
            path: String::new(),
            error: format!(
                "AlayaCore binary not found at '{}'. Set the ALAYACORE_BIN environment variable or install alayacore on PATH.",
                path
            ),
        },
    }
}

#[tauri::command]
pub async fn alayacore_reason(
    session_id: String,
    level: u32,
    sessions: State<'_, SessionMap>,
) -> Result<(), String> {
    let map = sessions.0.lock().await;
    send_cmd(&map, &session_id, "reason", &level.to_string())
        .await
        .map(|_| ())
}

#[tauri::command]
pub async fn alayacore_model_set(
    session_id: String,
    model_id: u32,
    sessions: State<'_, SessionMap>,
) -> Result<(), String> {
    let map = sessions.0.lock().await;
    send_cmd(&map, &session_id, "model_set", &model_id.to_string())
        .await
        .map(|_| ())
}

#[tauri::command]
pub async fn alayacore_model_sync(
    session_id: String,
    config: String,
    sessions: State<'_, SessionMap>,
) -> Result<(), String> {
    let map = sessions.0.lock().await;
    send_cmd(&map, &session_id, "model_sync", &config).await.map(|_| ())
}

#[tauri::command]
pub async fn alayacore_confirm(
    session_id: String,
    id: String,
    allowed: bool,
    sessions: State<'_, SessionMap>,
) -> Result<(), String> {
    let map = sessions.0.lock().await;
    let name = if allowed { "tool_confirm" } else { "tool_decline" };
    send_cmd(&map, &session_id, name, &id).await.map(|_| ())
}

#[tauri::command]
pub async fn alayacore_mcp_decline(
    session_id: String,
    server: String,
    sessions: State<'_, SessionMap>,
) -> Result<(), String> {
    let map = sessions.0.lock().await;
    send_cmd(&map, &session_id, "mcp_decline", &server)
        .await
        .map(|_| ())
}

#[tauri::command]
pub async fn alayacore_mcp_cancel(
    session_id: String,
    sessions: State<'_, SessionMap>,
) -> Result<(), String> {
    let map = sessions.0.lock().await;
    send_cmd(&map, &session_id, "mcp_cancel", "").await.map(|_| ())
}

#[cfg(test)]
mod tests {
    use super::*;

    // The two check_alayacore tests below mutate ALAYACORE_BIN / PATH /
    // cwd — all process-global. Without a process-wide lock, the tests
    // race each other (the missing-binary test can clobber the env vars
    // BEFORE the env-var test's check_alayacore call sees them). The
    // same pattern is used in dirs.rs::TEST_HOME_LOCK.
    static TEST_LOCK: std::sync::Mutex<()> = std::sync::Mutex::new(());

    /// check_alayacore must reflect the env-var override. A real
    /// executable file placed at ALAYACORE_BIN must be reported as
    /// ok=true with that path. A missing path must yield ok=false and
    /// a user-facing error that names the path that was tried.
    #[test]
    fn check_alayacore_env_var_points_to_real_file() {
        let _guard = TEST_LOCK.lock().unwrap();
        let dir = std::env::temp_dir().join(format!(
            "alayaface-check-bin-{}",
            std::process::id()
        ));
        std::fs::create_dir_all(&dir).unwrap();
        let bin = dir.join("alayacore");
        std::fs::write(&bin, b"#!/bin/sh\n").unwrap();
        std::env::set_var("ALAYACORE_BIN", &bin);

        let got = check_alayacore();
        assert!(got.ok, "ok=false for a real binary at {:?}", bin);
        assert_eq!(got.path, bin.to_string_lossy().to_string());
        assert!(got.error.is_empty(), "error must be empty on ok: {:?}", got.error);

        std::env::remove_var("ALAYACORE_BIN");
        let _ = std::fs::remove_dir_all(&dir);
    }

    #[test]
    fn check_alayacore_missing_binary_returns_error() {
        let _guard = TEST_LOCK.lock().unwrap();
        // Point ALAYACORE_BIN at a path that does NOT exist. Strip PATH
        // to an empty value so `which alayacore` fails, and chdir into
        // an empty temp dir so the relative candidate paths
        // ("alayacore", "../alayacore/alayacore", "./alayacore") cannot
        // resolve. FindBinary then falls back to the "alayacore" string,
        // which is not stat-able, so check_alayacore must report ok=false.
        let empty_path = std::env::temp_dir().join(format!(
            "alayaface-empty-path-{}",
            std::process::id()
        ));
        std::fs::create_dir_all(&empty_path).unwrap();
        let orig_path = std::env::var("PATH").unwrap_or_default();
        let missing = empty_path.join("not-alayacore");
        std::env::set_var("ALAYACORE_BIN", &missing);
        std::env::set_var("PATH", &empty_path);

        let orig_cwd = std::env::current_dir().unwrap();
        std::env::set_current_dir(&empty_path).unwrap();

        let got = check_alayacore();
        // Restore env before any assertions so a failure leaves the
        // process in a sane state for the next test.
        std::env::set_current_dir(orig_cwd).unwrap();
        std::env::set_var("PATH", orig_path);
        std::env::remove_var("ALAYACORE_BIN");

        assert!(!got.ok, "ok=true on a missing binary; path = {:?}", got.path);
        assert!(got.path.is_empty(), "path must be empty on ok=false: {:?}", got.path);
        assert!(!got.error.is_empty(), "error must be non-empty on ok=false");
        assert!(
            got.error.contains("not found"),
            "error must mention 'not found': {:?}",
            got.error
        );

        let _ = std::fs::remove_dir_all(&empty_path);
    }
}
