//! Simple command Tauri commands.
//!
//! Commands are sent to the session as CI (Command Input) frames:
//! `{"id":"<call-id>","name":"<command>","input":"<args-string>"}`.
//! Results arrive asynchronously as CO (Command Output) frames with the
//! same `id`, which the frontend renders (see reader.rs / Handlers.elm).
//! Uses the `send_cmd!` macro for fixed, argument-less commands.

use crate::commands::{send_cmd, SessionMap};
use crate::send_cmd;

use tauri::State;

// Simple commands with fixed text (generated by send_cmd! macro)
send_cmd!(alayacore_cancel, "cancel");
send_cmd!(alayacore_model_load, "model_load");
send_cmd!(alayacore_continue, "continue");
send_cmd!(alayacore_summarize, "summarize");

#[tauri::command]
pub async fn alayacore_model_set(
    session_id: String,
    model_id: u32,
    sessions: State<'_, SessionMap>,
) -> Result<(), String> {
    let map = sessions.0.lock().await;
    send_cmd(&map, &session_id, "model_set", &model_id.to_string())
        .await
        .map(|_| ())
}

#[tauri::command]
pub async fn alayacore_save(
    session_id: String,
    filename: String,
    sessions: State<'_, SessionMap>,
) -> Result<(), String> {
    let map = sessions.0.lock().await;
    send_cmd(&map, &session_id, "save", &filename).await.map(|_| ())
}

#[tauri::command]
pub async fn alayacore_fork(
    session_id: String,
    history_id: String,
    filename: String,
    sessions: State<'_, SessionMap>,
) -> Result<(), String> {
    let map = sessions.0.lock().await;
    let input = format!("{} {}", history_id, filename);
    send_cmd(&map, &session_id, "fork", &input).await.map(|_| ())
}

#[tauri::command]
pub async fn alayacore_reason(
    session_id: String,
    level: u32,
    sessions: State<'_, SessionMap>,
) -> Result<(), String> {
    let map = sessions.0.lock().await;
    send_cmd(&map, &session_id, "reason", &level.to_string())
        .await
        .map(|_| ())
}

#[tauri::command]
pub async fn alayacore_theme_set(
    session_id: String,
    name: String,
    sessions: State<'_, SessionMap>,
) -> Result<(), String> {
    let map = sessions.0.lock().await;
    send_cmd(&map, &session_id, "theme_set", &name).await.map(|_| ())
}

#[tauri::command]
pub async fn alayacore_model_sync(
    session_id: String,
    config: String,
    sessions: State<'_, SessionMap>,
) -> Result<(), String> {
    let map = sessions.0.lock().await;
    send_cmd(&map, &session_id, "model_sync", &config).await.map(|_| ())
}

#[tauri::command]
pub async fn alayacore_video_config(
    session_id: String,
    fps: u32,
    res: u32,
    sessions: State<'_, SessionMap>,
) -> Result<(), String> {
    let map = sessions.0.lock().await;
    let input = format!("{} {}", fps, res);
    send_cmd(&map, &session_id, "video_config", &input)
        .await
        .map(|_| ())
}

#[tauri::command]
pub async fn alayacore_confirm(
    session_id: String,
    id: String,
    allowed: bool,
    sessions: State<'_, SessionMap>,
) -> Result<(), String> {
    let map = sessions.0.lock().await;
    let name = if allowed { "tool_confirm" } else { "tool_decline" };
    send_cmd(&map, &session_id, name, &id).await.map(|_| ())
}

#[tauri::command]
pub async fn alayacore_mcp_decline(
    session_id: String,
    server: String,
    sessions: State<'_, SessionMap>,
) -> Result<(), String> {
    let map = sessions.0.lock().await;
    send_cmd(&map, &session_id, "mcp_decline", &server)
        .await
        .map(|_| ())
}

#[tauri::command]
pub async fn alayacore_mcp_cancel(
    session_id: String,
    sessions: State<'_, SessionMap>,
) -> Result<(), String> {
    let map = sessions.0.lock().await;
    send_cmd(&map, &session_id, "mcp_cancel", "").await.map(|_| ())
}
