//! Simple command Tauri commands.
//!
//! Commands that send a fixed or parametrized text to the session.
//! Uses the `send_cmd!` macro for simple one-liners.

use crate::commands::{send_raw, SessionMap};
use crate::tlv;
use crate::send_cmd;

use tauri::State;

// Simple commands with fixed text (generated by send_cmd! macro)
send_cmd!(alayacore_cancel, ":cancel");
send_cmd!(alayacore_model_load, ":model_load");
send_cmd!(alayacore_continue, ":continue");
send_cmd!(alayacore_summarize, ":summarize");

#[tauri::command]
pub async fn alayacore_model_set(
    session_id: String,
    model_id: u32,
    sessions: State<'_, SessionMap>,
) -> Result<(), String> {
    let map = sessions.0.lock().await;
    send_raw(&map, &session_id, tlv::TAG_USER_TEXT, &format!(":model_set {}", model_id)).await?;
    send_raw(&map, &session_id, tlv::TAG_USER_END, "").await
}

#[tauri::command]
pub async fn alayacore_save(
    session_id: String,
    filename: String,
    sessions: State<'_, SessionMap>,
) -> Result<(), String> {
    let map = sessions.0.lock().await;
    let cmd = if filename.is_empty() { ":save".to_string() } else { format!(":save {}", filename) };
    send_raw(&map, &session_id, tlv::TAG_USER_TEXT, &cmd).await?;
    send_raw(&map, &session_id, tlv::TAG_USER_END, "").await
}

#[tauri::command]
pub async fn alayacore_fork(
    session_id: String,
    history_id: String,
    filename: String,
    sessions: State<'_, SessionMap>,
) -> Result<(), String> {
    let map = sessions.0.lock().await;
    let cmd = format!(":fork {} {}", history_id, filename);
    send_raw(&map, &session_id, tlv::TAG_USER_TEXT, &cmd).await?;
    send_raw(&map, &session_id, tlv::TAG_USER_END, "").await
}

#[tauri::command]
pub async fn alayacore_reason(
    session_id: String,
    level: u32,
    sessions: State<'_, SessionMap>,
) -> Result<(), String> {
    let map = sessions.0.lock().await;
    send_raw(&map, &session_id, tlv::TAG_USER_TEXT, &format!(":reason {}", level)).await?;
    send_raw(&map, &session_id, tlv::TAG_USER_END, "").await
}

#[tauri::command]
pub async fn alayacore_theme_set(
    session_id: String,
    name: String,
    sessions: State<'_, SessionMap>,
) -> Result<(), String> {
    let map = sessions.0.lock().await;
    send_raw(&map, &session_id, tlv::TAG_USER_TEXT, &format!(":theme_set {}", name)).await?;
    send_raw(&map, &session_id, tlv::TAG_USER_END, "").await
}

#[tauri::command]
pub async fn alayacore_model_sync(
    session_id: String,
    config: String,
    sessions: State<'_, SessionMap>,
) -> Result<(), String> {
    let map = sessions.0.lock().await;
    send_raw(&map, &session_id, tlv::TAG_USER_TEXT, &format!(":model_sync {}", config)).await?;
    send_raw(&map, &session_id, tlv::TAG_USER_END, "").await
}

#[tauri::command]
pub async fn alayacore_video_config(
    session_id: String,
    fps: u32,
    res: u32,
    sessions: State<'_, SessionMap>,
) -> Result<(), String> {
    let map = sessions.0.lock().await;
    send_raw(&map, &session_id, tlv::TAG_USER_TEXT, &format!(":video_config {} {}", fps, res)).await?;
    send_raw(&map, &session_id, tlv::TAG_USER_END, "").await
}

#[tauri::command]
pub async fn alayacore_confirm(
    session_id: String,
    id: String,
    allowed: bool,
    sessions: State<'_, SessionMap>,
) -> Result<(), String> {
    let map = sessions.0.lock().await;
    let cmd = if allowed {
        format!(":tool_confirm {}", id)
    } else {
        format!(":tool_decline {}", id)
    };
    send_raw(&map, &session_id, tlv::TAG_USER_TEXT, &cmd).await?;
    send_raw(&map, &session_id, tlv::TAG_USER_END, "").await
}
