package handlers

import (
	"bytes"
	"crypto/rand"
	"encoding/base64"
	"encoding/binary"
	"encoding/json"
	"fmt"
	"io"
	"log"
	"mime/multipart"
	"net/http"
	"os"
	"strings"
	"time"

	"alayaface/src-go/internal/dirs"
)

// Wire protocol constants.
const (
	ProtocolTranscriptions  = "transcriptions"
	ProtocolChatCompletions = "chat_completions"
	ProtocolStepAudio       = "step_audio"
)

// AsrProfile is one ASR endpoint configuration (a named profile).
type AsrProfile struct {
	// Stable id (generated by the backend when empty).
	ID string `json:"id"`
	// Display name shown in the ASR config list.
	Name string `json:"name"`
	// Wire protocol: "transcriptions" (default) or "chat_completions".
	Protocol string `json:"protocol"`
	// FULL endpoint address, e.g.
	// "http://127.0.0.1:8080/v1/audio/transcriptions" (local) or
	// "https://api.openai.com/v1/audio/transcriptions" /
	// "https://api.xiaomimimo.com/v1/chat/completions" (remote). Used
	// verbatim — nothing is appended.
	URL string `json:"url"`
	// API key. transcriptions: Authorization: Bearer; chat_completions:
	// api-key header. Empty = no header (local endpoints usually don't
	// require one).
	APIKey string `json:"api_key"`
	// Model id passed through to the endpoint (default "whisper-1").
	Model string `json:"model"`
	// Language hint; "auto" (default) = autodetect.
	Language string `json:"language"`
}

// AsrConfig is the voice-input ASR config (~/.alayaface/asr.conf): the
// profile list plus the active profile id. Like global.conf, this file
// applies to every preset.
type AsrConfig struct {
	// Id of the profile used by asr_transcribe. Falls back to the first
	// profile when it does not reference an existing one.
	Active string `json:"active"`
	// All configured ASR endpoints.
	Profiles []AsrProfile `json:"profiles"`
}

// DefaultAsrConfig is used when asr.conf is missing or empty.
func DefaultAsrConfig() AsrConfig {
	return AsrConfig{}
}

// newProfileID returns a random hex id for a profile.
func newProfileID() string {
	b := make([]byte, 8)
	if _, err := rand.Read(b); err != nil {
		return fmt.Sprintf("asr-%d", time.Now().UnixNano())
	}
	return fmt.Sprintf("%x", b)
}

// NormalizeAsrProfile fixes one profile: assign a fresh id when empty,
// default the name to the URL, fix protocol/model/language defaults.
func NormalizeAsrProfile(p *AsrProfile) {
	if strings.TrimSpace(p.ID) == "" {
		p.ID = newProfileID()
	}
	if strings.TrimSpace(p.Name) == "" {
		if strings.TrimSpace(p.URL) == "" {
			p.Name = "ASR"
		} else {
			p.Name = strings.TrimSpace(p.URL)
		}
	}
	if p.Protocol != ProtocolChatCompletions && p.Protocol != ProtocolStepAudio {
		p.Protocol = ProtocolTranscriptions
	}
	if strings.TrimSpace(p.Model) == "" {
		p.Model = "whisper-1"
	}
	if strings.TrimSpace(p.Language) == "" {
		p.Language = "auto"
	}
}

// NormalizeAsrConfig fixes the whole config: every profile plus `active`
// referencing an existing profile (empty → first, stale → first).
func NormalizeAsrConfig(cfg *AsrConfig) {
	for i := range cfg.Profiles {
		NormalizeAsrProfile(&cfg.Profiles[i])
	}
	activeOK := false
	for _, p := range cfg.Profiles {
		if p.ID == strings.TrimSpace(cfg.Active) {
			activeOK = true
			break
		}
	}
	if strings.TrimSpace(cfg.Active) == "" || !activeOK {
		if len(cfg.Profiles) > 0 {
			cfg.Active = cfg.Profiles[0].ID
		} else {
			cfg.Active = ""
		}
	}
}

// activeAsrProfile returns the profile asr_transcribe should use: the
// active one, falling back to the first when active is stale/empty.
func activeAsrProfile(cfg *AsrConfig) *AsrProfile {
	for i := range cfg.Profiles {
		if cfg.Profiles[i].ID == cfg.Active {
			return &cfg.Profiles[i]
		}
	}
	if len(cfg.Profiles) > 0 {
		return &cfg.Profiles[0]
	}
	return nil
}

// readAsrConfig reads the ASR config; a missing/empty file yields
// defaults. Parse errors are reported (a corrupt asr.conf must not be
// silently ignored).
func readAsrConfig() (AsrConfig, error) {
	path := dirs.AsrConfigFile()
	text, err := os.ReadFile(path)
	if err != nil {
		if os.IsNotExist(err) {
			return DefaultAsrConfig(), nil
		}
		return AsrConfig{}, err
	}
	if strings.TrimSpace(string(text)) == "" {
		return DefaultAsrConfig(), nil
	}
	var cfg AsrConfig
	if err := json.Unmarshal(text, &cfg); err != nil {
		return AsrConfig{}, fmt.Errorf("Failed to parse asr.conf: %w", err)
	}
	NormalizeAsrConfig(&cfg)
	return cfg, nil
}

// GetAsrConfig returns the ASR config overlay.
func GetAsrConfig(h *Handler, w http.ResponseWriter, r *http.Request) error {
	cfg, err := readAsrConfig()
	if err != nil {
		return err
	}
	return writeJSON(w, cfg)
}

// SyncAsrConfig replaces the ASR config overlay. Accepts
// {"active": id, "profiles": [...]} (any subset of fields); writes
// atomically. The normalized config is returned so the frontend can
// adopt the effective values (including generated profile ids).
func SyncAsrConfig(h *Handler, w http.ResponseWriter, r *http.Request) error {
	var args struct {
		Config string `json:"config"`
	}
	if err := decodeArgs(r, &args); err != nil {
		return err
	}
	var cfg AsrConfig
	if err := json.Unmarshal([]byte(args.Config), &cfg); err != nil {
		return fmt.Errorf("Invalid ASR config JSON: %w", err)
	}
	NormalizeAsrConfig(&cfg)

	if _, err := dirs.Ensure(); err != nil {
		return err
	}
	path := dirs.AsrConfigFile()
	tmp := path + ".tmp"
	text, err := json.MarshalIndent(cfg, "", "  ")
	if err != nil {
		return err
	}
	if err := os.WriteFile(tmp, text, 0o644); err != nil {
		return err
	}
	if err := os.Rename(tmp, path); err != nil {
		return err
	}
	return writeResult(w, cfg)
}

// AsrTranscribeResult is the transcription outcome. Ok is true when the
// endpoint responded with a transcript (possibly empty text for
// silence); Error carries the human-readable reason otherwise.
type AsrTranscribeResult struct {
	Ok    bool   `json:"ok"`
	Text  string `json:"text"`
	Error string `json:"error"`
}

// AsrTranscribe transcribes base64-encoded WAV audio with the ACTIVE
// ASR profile. The session id is used for logging only — transcription
// is stateless.
func AsrTranscribe(h *Handler, w http.ResponseWriter, r *http.Request) error {
	var args struct {
		AudioBase64 string `json:"audioBase64"`
		SessionID   string `json:"sessionId"`
	}
	if err := decodeArgs(r, &args); err != nil {
		return err
	}
	// Log the outgoing request (audio base64 truncated to a short
	// preview) so ASR endpoint issues are diagnosable from the backend.
	head := args.AudioBase64
	if len(head) > 120 {
		head = head[:120]
	}
	log.Printf("[asr] transcribe session=%s payload=%db head=%s…", args.SessionID, len(args.AudioBase64), head)
	wav, err := base64.StdEncoding.DecodeString(args.AudioBase64)
	if err != nil {
		return fmt.Errorf("Invalid audio payload: %w", err)
	}
	if len(wav) == 0 {
		return writeResult(w, AsrTranscribeResult{Ok: false, Error: "Empty audio"})
	}
	cfg, err := readAsrConfig()
	if err != nil {
		return err
	}
	p := activeAsrProfile(&cfg)
	if p == nil {
		return writeResult(w, AsrTranscribeResult{Ok: false, Error: "ASR not configured: add an endpoint in the ASR config"})
	}
	if strings.TrimSpace(p.URL) == "" {
		return writeResult(w, AsrTranscribeResult{Ok: false, Error: "ASR not configured: set the endpoint URL in the ASR config"})
	}
	var res AsrTranscribeResult
	if p.Protocol == ProtocolChatCompletions {
		res = asrTranscribeChat(*p, args.AudioBase64, wav)
	} else if p.Protocol == ProtocolStepAudio {
		res = asrTranscribeStepAudio(*p, wav)
	} else {
		res = asrTranscribeMultipart(*p, wav)
	}
	return writeResult(w, res)
}

// asrTranscribeMultipart POSTs the WAV as multipart to the profile's
// endpoint URL (used verbatim) and parses {"text": ...}.
func asrTranscribeMultipart(p AsrProfile, wav []byte) AsrTranscribeResult {
	url := strings.TrimSpace(p.URL)
	if url == "" {
		return AsrTranscribeResult{Ok: false, Error: "ASR not configured: set the endpoint URL in the ASR config"}
	}
	model := strings.TrimSpace(p.Model)
	if model == "" {
		model = "whisper-1"
	}
	lang := strings.TrimSpace(p.Language)

	// The wire format is multipart/form-data; the hex head shows the WAV
	// begins with "RIFF" (52 49 46 46) when the encoder produced a valid
	// file.
	wavHead := ""
	if len(wav) > 16 {
		wavHead = fmt.Sprintf("%x", wav[:16])
	} else {
		wavHead = fmt.Sprintf("%x", wav)
	}
	log.Printf("[asr] POST %s profile=%s model=%s lang=%s wav=%db head=%s", url, p.Name, model, lang, len(wav), wavHead)

	var buf bytes.Buffer
	mw := multipart.NewWriter(&buf)
	fw, err := mw.CreateFormFile("file", "audio.wav")
	if err != nil {
		return AsrTranscribeResult{Ok: false, Error: err.Error()}
	}
	if _, err := fw.Write(wav); err != nil {
		return AsrTranscribeResult{Ok: false, Error: err.Error()}
	}
	if err := mw.WriteField("model", model); err != nil {
		return AsrTranscribeResult{Ok: false, Error: err.Error()}
	}
	if lang != "" && lang != "auto" {
		if err := mw.WriteField("language", lang); err != nil {
			return AsrTranscribeResult{Ok: false, Error: err.Error()}
		}
	}
	if err := mw.Close(); err != nil {
		return AsrTranscribeResult{Ok: false, Error: err.Error()}
	}

	req, err := http.NewRequest(http.MethodPost, url, &buf)
	if err != nil {
		return AsrTranscribeResult{Ok: false, Error: err.Error()}
	}
	req.Header.Set("Content-Type", mw.FormDataContentType())
	if key := strings.TrimSpace(p.APIKey); key != "" {
		req.Header.Set("Authorization", "Bearer "+key)
	}
	res := doAsrRequest(req, "multipart")
	if !res.Ok || res.Error != "" {
		return res
	}
	var out struct {
		Text string `json:"text"`
	}
	if err := json.Unmarshal([]byte(res.Text), &out); err != nil {
		return AsrTranscribeResult{Ok: false, Error: "Bad ASR response: " + err.Error()}
	}
	return AsrTranscribeResult{Ok: true, Text: strings.TrimSpace(out.Text)}
}

// asrTranscribeChat POSTs a chat-completions style ASR request (e.g.
// MiMo): JSON body carrying the audio base64 as an input_audio content
// part, api-key header, streamed response. The transcript is read from
// the SSE delta stream; a plain JSON response is accepted as a fallback.
func asrTranscribeChat(p AsrProfile, audioBase64 string, wav []byte) AsrTranscribeResult {
	url := strings.TrimSpace(p.URL)
	if url == "" {
		return AsrTranscribeResult{Ok: false, Error: "ASR not configured: set the endpoint URL in the ASR config"}
	}
	model := strings.TrimSpace(p.Model)
	if model == "" {
		model = "whisper-1"
	}
	lang := strings.TrimSpace(p.Language)
	if lang == "" {
		lang = "auto"
	}

	body, err := json.Marshal(map[string]any{
		"model": model,
		"messages": []map[string]any{
			{
				"role": "user",
				"content": []map[string]any{
					{
						"type": "input_audio",
						"input_audio": map[string]any{
							"data":   audioBase64,
							"format": "wav",
						},
					},
				},
			},
		},
		"asr_options": map[string]any{"language": lang},
		"stream":      true,
	})
	if err != nil {
		return AsrTranscribeResult{Ok: false, Error: err.Error()}
	}

	wavHead := ""
	if len(wav) > 16 {
		wavHead = fmt.Sprintf("%x", wav[:16])
	} else {
		wavHead = fmt.Sprintf("%x", wav)
	}
	log.Printf("[asr] POST %s profile=%s protocol=chat_completions model=%s lang=%s wav=%db head=%s", url, p.Name, model, lang, len(wav), wavHead)

	req, err := http.NewRequest(http.MethodPost, url, bytes.NewReader(body))
	if err != nil {
		return AsrTranscribeResult{Ok: false, Error: err.Error()}
	}
	req.Header.Set("Content-Type", "application/json")
	if key := strings.TrimSpace(p.APIKey); key != "" {
		req.Header.Set("api-key", key)
	}
	res := doAsrRequest(req, "chat_completions")
	if !res.Ok || res.Error != "" {
		return res
	}
	return AsrTranscribeResult{Ok: true, Text: extractChatText(res.Text), Error: ""}
}

// asrTranscribeStepAudio POSTs a StepFun StepAudio realtime ASR request:
// JSON body with audio.data = RAW PCM base64 (the WAV container from the
// webview is stripped here; the format fields are read from the WAV
// header so they always match the actual audio), Accept:
// text/event-stream, Authorization: Bearer. SSE events:
// transcript.text.delta accumulates, transcript.text.done carries the
// final text (fallback to accumulated deltas), error aborts.
func asrTranscribeStepAudio(p AsrProfile, wav []byte) AsrTranscribeResult {
	url := strings.TrimSpace(p.URL)
	if url == "" {
		return AsrTranscribeResult{Ok: false, Error: "ASR not configured: set the endpoint URL in the ASR config"}
	}
	rate, channels, bits, dataOffset, dataSize, ok := wavParams(wav)
	if !ok {
		return AsrTranscribeResult{Ok: false, Error: "Invalid WAV audio: expected 16-bit PCM mono (RIFF/WAVE)"}
	}
	if bits != 16 || channels != 1 {
		return AsrTranscribeResult{Ok: false, Error: fmt.Sprintf("StepAudio needs 16-bit mono PCM, got %d-bit x %d ch", bits, channels)}
	}
	// Slice exactly the `data` chunk's payload — NOT everything after
	// the header: a WAV may carry trailing chunks (LIST/ID3 metadata)
	// past the audio, and shipping those as PCM corrupts the stream.
	if dataOffset+dataSize > len(wav) {
		// Truncated file: the declared size overruns the buffer. Clamp
		// rather than reject so a short-but-real recording still works.
		dataSize = len(wav) - dataOffset
	}
	pcm := wav[dataOffset : dataOffset+dataSize]
	pcmBase64 := base64.StdEncoding.EncodeToString(pcm)
	model := strings.TrimSpace(p.Model)
	if model == "" {
		model = "stepaudio-2.5-asr"
	}
	lang := strings.TrimSpace(p.Language)
	if lang == "" {
		lang = "auto"
	}

	body, err := json.Marshal(map[string]any{
		"audio": map[string]any{
			"data": pcmBase64,
			"input": map[string]any{
				"transcription": map[string]any{
					"language":         lang,
					"hotwords":         []string{},
					"model":            model,
					"enable_itn":       true,
					"enable_timestamp": true,
				},
				"format": map[string]any{
					"type":    "pcm",
					"codec":   "pcm_s16le",
					"rate":    rate,
					"bits":    bits,
					"channel": channels,
				},
			},
		},
	})
	if err != nil {
		return AsrTranscribeResult{Ok: false, Error: err.Error()}
	}

	log.Printf("[asr] POST %s profile=%s protocol=step_audio model=%s lang=%s pcm=%db rate=%d bits=%d ch=%d", url, p.Name, model, lang, len(pcm), rate, bits, channels)

	req, err := http.NewRequest(http.MethodPost, url, bytes.NewReader(body))
	if err != nil {
		return AsrTranscribeResult{Ok: false, Error: err.Error()}
	}
	req.Header.Set("Content-Type", "application/json")
	req.Header.Set("Accept", "text/event-stream")
	if key := strings.TrimSpace(p.APIKey); key != "" {
		req.Header.Set("Authorization", "Bearer "+key)
	}
	res := doAsrRequest(req, "step_audio")
	if !res.Ok || res.Error != "" {
		return res
	}
	transcript, err := extractStepAudioText(res.Text)
	if err != nil {
		return AsrTranscribeResult{Ok: false, Error: "StepAudio error: " + err.Error()}
	}
	return AsrTranscribeResult{Ok: true, Text: transcript, Error: ""}
}

// wavParams parses a standard PCM WAV header: (sample rate, channels,
// bits per sample, offset of the PCM data, size of the PCM data). Only
// uncompressed PCM (audio format 1) is accepted, and the `fmt ` chunk
// must precede the `data` chunk. Chunks are scanned so fmt extensions
// are handled; the data chunk's size is returned so callers can slice
// exactly the audio and skip any trailing metadata chunks.
func wavParams(wav []byte) (rate uint32, channels uint16, bits uint16, dataOffset int, dataSize int, ok bool) {
	if len(wav) < 12 || string(wav[0:4]) != "RIFF" || string(wav[8:12]) != "WAVE" {
		return 0, 0, 0, 0, 0, false
	}
	pos := 12
	haveFmt := false
	for pos+8 <= len(wav) {
		id := string(wav[pos : pos+4])
		size := int(binary.LittleEndian.Uint32(wav[pos+4 : pos+8]))
		if id == "fmt " && size >= 16 && pos+8+24 <= len(wav) {
			if binary.LittleEndian.Uint16(wav[pos+8:pos+10]) != 1 {
				return 0, 0, 0, 0, 0, false
			}
			channels = binary.LittleEndian.Uint16(wav[pos+10 : pos+12])
			rate = binary.LittleEndian.Uint32(wav[pos+12 : pos+16])
			bits = binary.LittleEndian.Uint16(wav[pos+22 : pos+24])
			haveFmt = true
		} else if id == "data" {
			// A data chunk before fmt means the header is malformed —
			// the format fields would all be zero.
			if !haveFmt {
				return 0, 0, 0, 0, 0, false
			}
			return rate, channels, bits, pos + 8, size, true
		}
		pos += 8 + size + (size % 2)
	}
	return 0, 0, 0, 0, 0, false
}

// extractStepAudioText extracts the transcript from a StepAudio SSE
// response:
//   - transcript.text.delta → accumulate `delta`
//   - transcript.text.done → return its `text` (fallback: accumulated)
//   - error → non-nil error with its message
func extractStepAudioText(body string) (string, error) {
	var text strings.Builder
	for _, line := range strings.Split(body, "\n") {
		line = strings.TrimSpace(line)
		payload, ok := strings.CutPrefix(line, "data:")
		if !ok {
			continue
		}
		payload = strings.TrimSpace(payload)
		if payload == "" {
			continue
		}
		var v struct {
			Type    string `json:"type"`
			Delta   string `json:"delta"`
			Text    string `json:"text"`
			Message string `json:"message"`
		}
		if err := json.Unmarshal([]byte(payload), &v); err != nil {
			continue
		}
		switch v.Type {
		case "transcript.text.delta":
			text.WriteString(v.Delta)
		case "transcript.text.done":
			if strings.TrimSpace(v.Text) != "" {
				return strings.TrimSpace(v.Text), nil
			}
			return strings.TrimSpace(text.String()), nil
		case "error":
			if v.Message == "" {
				v.Message = "unknown error"
			}
			return "", fmt.Errorf("%s", v.Message)
		}
	}
	return strings.TrimSpace(text.String()), nil
}

// doAsrRequest runs the request, logs the response, and returns either
// an error result (non-2xx / read failure) or the raw body in Text.
func doAsrRequest(req *http.Request, proto string) AsrTranscribeResult {
	client := &http.Client{Timeout: 120 * time.Second}
	resp, err := client.Do(req)
	if err != nil {
		return AsrTranscribeResult{Ok: false, Error: "ASR request failed: " + err.Error()}
	}
	defer resp.Body.Close()
	raw, err := io.ReadAll(io.LimitReader(resp.Body, 1<<20))
	if err != nil {
		return AsrTranscribeResult{Ok: false, Error: "ASR response read failed: " + err.Error()}
	}
	preview := string(raw)
	if len(preview) > 300 {
		preview = preview[:300]
	}
	log.Printf("[asr] response %s body=%s", resp.Status, preview)
	if resp.StatusCode < 200 || resp.StatusCode >= 300 {
		return AsrTranscribeResult{Ok: false, Error: fmt.Sprintf("ASR API returned %s: %s", resp.Status, preview)}
	}
	return AsrTranscribeResult{Ok: true, Text: string(raw), Error: ""}
}

// extractChatText extracts the transcript from a chat-completions
// response: SSE `data:` lines (delta/message content, stopped by
// `data: [DONE]`), falling back to a plain JSON body.
func extractChatText(body string) string {
	var text strings.Builder
	for _, line := range strings.Split(body, "\n") {
		line = strings.TrimSpace(line)
		payload, ok := strings.CutPrefix(line, "data:")
		if !ok {
			continue
		}
		payload = strings.TrimSpace(payload)
		if payload == "[DONE]" {
			break
		}
		var v struct {
			Choices []struct {
				Delta   map[string]any `json:"delta"`
				Message map[string]any `json:"message"`
			} `json:"choices"`
		}
		if err := json.Unmarshal([]byte(payload), &v); err != nil {
			continue
		}
		for _, c := range v.Choices {
			if s, _ := c.Delta["content"].(string); s != "" {
				text.WriteString(s)
			} else if s, _ := c.Message["content"].(string); s != "" {
				text.WriteString(s)
			}
		}
	}
	if text.Len() == 0 {
		// Not an SSE stream (some servers ignore `stream`): plain JSON.
		var v struct {
			Choices []struct {
				Message map[string]any `json:"message"`
			} `json:"choices"`
		}
		if err := json.Unmarshal([]byte(body), &v); err == nil {
			for _, c := range v.Choices {
				if s, _ := c.Message["content"].(string); s != "" {
					text.WriteString(s)
				}
			}
		}
	}
	return strings.TrimSpace(text.String())
}
